### ISSUE TITLE
difficulty getting this to work

### ISSUE THREAD

**Issue by kamipatel** [Snowflake-Labs/aws-integrations-cloudops#1]
Hi,

I work for Salesforce and I would like to get this working for a very big use case. 

It was very difficult to follow the blog's installation instructions. I finally reached last step and product launch is is failing.
kindly clarify following... Thanks!

1 - Upload the snowflakelayer.zip in the root folder of this S3 bucket. 
Q: Which root folder? 

2 - When I launch the "SnowflakeStorageIntegrationProduct", what should be the values of this?
S3BUCKETNAME - Is this s3-snowflakeintegration-account-region bucket? Or this will be created by snowflake?
S3BUCKETPREFIX- What about this?
snowschema - Do I need to create schema first?
snowtable - Do I need to create table first?

Thanks,
Kam

**Comment by kmmahaj** [comment]
1. The root folder is simply the root location of the S3 bucket. So, in this case the bucket is  's3-snowflakeintegration-account-region' and you would upload the zip file directly there to the bucket
2. SnowflakeStorageIntegrationProduct value is autogenerated. If you don't click the box for autogeneration, you can supply any value as the name of the product
3. S3BUCKETNAME and S3BUCKETPREFIX are the name and prefix of the S3 Bucket to which you want to extend the Snowflake integration.
4. Yes you need a snowflake account  - and snowschema and snowtable are the snowflake objects that are needed in your account.
